julia -e 'using MLJ' && \
julia -e 'using Flux' && \
julia -e 'using GR' && \
julia -e 'using Plots' && \
julia -e 'using Distributions' && \
julia -e 'using Optim' && \
julia -e 'using StatsPlots' && \
julia -e 'using IJulia' && \
julia -e 'using Revise' && \
julia -e 'using LightGraphs' && \
julia -e 'using DataStructures' && \
julia -e 'using DataFrames' && \
julia -e 'using Cxx' && \
julia -e 'using PyCall' && \
julia -e 'using DifferentialEquations' && \
julia -e 'using JuMP' && \
julia -e 'using JuliaDB' && \
julia -e 'using Images' && \
julia -e 'using FileIO' && \
julia -e 'using BSON' && \
julia -e 'using StatsBase' && \
julia -e 'using MultivariateStats' && \
julia -e 'using ScikitLearn' && \
julia -e 'using Optim' && \
julia -e 'using Weave' && \
julia -e 'using Distances'
